# -*- coding: utf-8 -*-
"""Health Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1neZ7pqpjhV636D6I90EXrKVtOhDvhPkh

**Step 1: Install dependencies**
"""

!pip install transformers torch

"""**Use Instruction Model**"""

from transformers import pipeline

chatbot = pipeline(
    "text-generation",
    model="mistralai/Mistral-7B-Instruct-v0.1",
    device=0
)

"""**Updated function for Mistral**"""

def ask_health_question(user_input):
    prompt = f"""
    You are a helpful and safe medical assistant.

    Question: {user_input}
    Answer:
    """

    response = chatbot(
        prompt,
        max_new_tokens=150,
        do_sample=True,
        temperature=0.7
    )

    return response[0]['generated_text']

while True:
    query = input("Ask a question: ")

    if query.lower() == "exit":
        break

    print(ask_health_question(query))

"""**Add Safety Layer**"""

def safety_filter(user_input):
    risky_keywords = [
        "suicide", "kill myself", "overdose", "emergency", "die"
    ]

    for word in risky_keywords:
        if word in user_input.lower():
            return False
    return True

"""**Clean Response Extraction**"""

def clean_response(output):
    if "Answer:" in output:
        return output.split("Answer:")[-1].strip()
    return output.strip()

"""**Combine Everything**"""

def safe_chatbot(user_input):
    if not safety_filter(user_input):
        return "⚠️ Please seek immediate help from a medical professional."

    raw_output = ask_health_question(user_input)
    return clean_response(raw_output)

"""**Build Interactive Chat Loop**"""

def run_chatbot():
    print("🩺 Health Assistant Chatbot")
    print("Type 'exit' to quit\n")

    while True:
        user_input = input("You: ")

        if user_input.lower() == "exit":
            print("Goodbye!")
            break

        response = safe_chatbot(user_input)
        print("Bot:", response)

run_chatbot()

"""**Improve Output Quality**"""

def ask_health_question(user_input):
    prompt = f"""
    You are a helpful and safe medical assistant.

    Answer in this format:
    - Explanation:
    - Advice:
    - When to see a doctor:

    Question: {user_input}
    Answer:
    """

    response = chatbot(
        prompt,
        max_new_tokens=150,
        do_sample=True,
        temperature=0.7
    )

    return response[0]['generated_text']

"""**Add Memory**"""

chat_history = []

def chatbot_with_memory(user_input):
    chat_history.append(f"User: {user_input}")

    context = "\n".join(chat_history[-5:])  # last 5 messages

    prompt = f"""
    You are a helpful medical assistant.

    Conversation:
    {context}

    Assistant:
    """

    response = chatbot(prompt, max_new_tokens=150)

    reply = response[0]['generated_text']
    chat_history.append(f"Bot: {reply}")

    return reply