# -*- coding: utf-8 -*-
"""HeartDiseasePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orMpKLOf4O7LDsiLRP_3G4HIrGwwIxcG

**Step 1: Install Dependencies**
"""

!pip install pandas numpy matplotlib seaborn scikit-learn openai

"""**Step 2: Import Libraries**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve

"""**Step 3 : Load Dataset**
## Dataset

Download dataset from:
https://www.kaggle.com/datasets/johnsmith88/heart-disease-dataset

Place `heart.csv` in the same directory before running.
"""

import pandas as pd
df = pd.read_csv("heart.csv")
df.head()

"""**Step 4 : Data Exploration**"""

print(df.shape)
print(df.info())
print(df.describe())

"""**Step 5: Visualization**"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='target', data=df)
plt.title("Heart Disease Distribution")
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.show()

"""**Step 6: Preprocessing**"""

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

"""**Step 7: Train Model**"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

"""**Step 8: Evaluation**"""

from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True)
plt.title("Confusion Matrix")
plt.show()

# ROC Curve
y_probs = model.predict_proba(X_test)[:,1]
fpr, tpr, _ = roc_curve(y_test, y_probs)

plt.plot(fpr, tpr)
plt.title("ROC Curve")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.show()

print("ROC-AUC:", roc_auc_score(y_test, y_probs))

"""**Step 9 : Highlight important features affecting prediction**"""

importance = model.coef_[0]
features = X.columns

sns.barplot(x=importance, y=features)
plt.title("Feature Importance")
plt.show()